namespace XState.Scxml;

/// <summary>SCXML §5.10 <c>_event.type</c>: where the event came from.</summary>
public enum ScxmlEventKind
{
    /// <summary>Raised by <c>&lt;raise&gt;</c> or <c>&lt;send target="#_internal"&gt;</c>.</summary>
    Internal,

    /// <summary>Delivered from the external queue (<c>&lt;send&gt;</c>, host, invoked children).</summary>
    External,

    /// <summary>Generated by the platform itself (<c>error.execution</c>, <c>done.*</c>, …).</summary>
    Platform
}

/// <summary>
/// An SCXML event. Like <see cref="NamedEvent"/> it is identified by its string name, but it
/// additionally carries the SCXML §5.10 <c>_event</c> fields so that expressions evaluated in
/// the datamodel can observe <c>_event.type</c>, <c>_event.sendid</c>, <c>_event.origintype</c>
/// and <c>_event.invokeid</c>.
/// </summary>
public sealed record ScxmlEvent(string Name, object? Data = null) : MachineEvent
{
    /// <summary>The SCXML event processor URI used as the default <c>origintype</c>.</summary>
    public const string ScxmlEventProcessor = "http://www.w3.org/TR/scxml/#SCXMLEventProcessor";

    public override string Type => Name;

    public ScxmlEventKind Kind { get; init; } = ScxmlEventKind.External;

    /// <summary>The <c>id</c> of the <c>&lt;send&gt;</c> that produced this event, if any.</summary>
    public string? SendId { get; init; }

    /// <summary>Best-effort origin (the sender's address).</summary>
    public string? Origin { get; init; }

    /// <summary>Best-effort origin type (the event I/O processor URI).</summary>
    public string? OriginType { get; init; }

    /// <summary>Set when the event was delivered by an invoked child.</summary>
    public string? InvokeId { get; init; }

    /// <summary>An internal-queue event (<c>&lt;raise&gt;</c>).</summary>
    public static ScxmlEvent Raised(string name, object? data = null) =>
        new(name, data) { Kind = ScxmlEventKind.Internal };

    /// <summary>A platform event such as <c>error.execution</c>.</summary>
    public static ScxmlEvent Platform(string name, object? data = null) =>
        new(name, data) { Kind = ScxmlEventKind.Platform };

    /// <summary>SCXML <c>error.execution</c>, raised on any expression/executable-content failure.</summary>
    public static ScxmlEvent ExecutionError(string? message = null) =>
        Platform("error.execution", message);

    /// <summary>SCXML <c>error.communication</c>, raised when an event cannot be delivered.</summary>
    public static ScxmlEvent CommunicationError(string? message = null) =>
        Platform("error.communication", message);
}

/// <summary>
/// Maps core <see cref="MachineEvent"/>s onto SCXML event names and matches them against
/// SCXML event descriptors (§3.12.1 / Appendix B token-prefix matching).
/// </summary>
public static class ScxmlEventNaming
{
    /// <summary>The SCXML event name for a core event (<c>done.state.x</c>, <c>done.invoke.y</c>, …).</summary>
    public static string NameOf(MachineEvent evt) => evt switch
    {
        ScxmlEvent e => e.Name,
        NamedEvent e => e.Name,
        DoneStateEvent e => $"done.state.{e.StateId}",
        DoneActorEvent e => $"done.invoke.{e.ActorId}",
        ErrorActorEvent => "error.communication",
        ErrorPlatformEvent e => $"error.{e.Kind}",
        _ => evt.Type
    };

    /// <summary>The SCXML <c>_event.type</c> for a core event.</summary>
    public static ScxmlEventKind KindOf(MachineEvent evt) => evt switch
    {
        ScxmlEvent e => e.Kind,
        DoneStateEvent or DoneActorEvent or ErrorActorEvent or ErrorPlatformEvent or InitEvent
            or AfterEvent or TimeoutEvent or ActorTimeoutEvent => ScxmlEventKind.Platform,
        _ => ScxmlEventKind.External
    };

    /// <summary>The payload exposed as <c>_event.data</c>.</summary>
    public static object? DataOf(MachineEvent evt) => evt switch
    {
        ScxmlEvent e => e.Data,
        NamedEvent e => e.Data,
        DoneStateEvent e => e.Output,
        DoneActorEvent e => e.Output,
        ErrorActorEvent e => e.Error.Message,
        InitEvent e => e.Input,
        _ => null
    };

    /// <summary>
    /// SCXML descriptor matching: <c>"*"</c> matches everything, a trailing <c>".*"</c> is
    /// ignored, and a descriptor matches an event name that is equal to it or is a
    /// dot-separated descendant of it (<c>"error"</c> matches <c>"error.execution"</c>).
    /// </summary>
    public static bool Matches(string descriptor, string eventName)
    {
        if (descriptor.Length == 0 || descriptor == "*")
        {
            return true;
        }

        var prefix = descriptor;
        while (prefix.EndsWith(".*", StringComparison.Ordinal))
        {
            prefix = prefix[..^2];
        }

        prefix = prefix.TrimEnd('.');

        return prefix.Length == 0 ||
               eventName == prefix ||
               eventName.StartsWith(prefix + ".", StringComparison.Ordinal);
    }
}
